### ISSUE TITLE
Multiple images

### ISSUE THREAD

**Issue by Amithvassit** [fcakyon/craft-text-detector#16]
How to run craft model using for loop , without memory error , If I run craft on multiple images using for loop, I'm facing memory segmentation issue

**Comment by fcakyon** [comment]
Can you give a minimal code sample to recreate the issue? Which function are you using in a for loop?

**Comment by Amithvassit** [comment]
I was using the Advanced usage example,But I loaded the model only once ,
and I was running for loop on this function.
prediction_result = get_prediction(
    image=image,
    craft_net=craft_net,
    refine_net=refine_net,
    text_threshold=0.7,
    link_threshold=0.4,
    low_text=0.4,
    cuda=True,
    long_size=1280
)

**Comment by fcakyon** [comment]
@Amithvassit Have you tried calling the function with cuda=False argument? 

At the moment I dont have a check for the case when computer doesnt have any gpu and function is called with cuda=True.
