### ISSUE TITLE
How can we Batch Processing?

### ISSUE THREAD

**Issue by abhiksark** [fcakyon/craft-text-detector#17]
I check the code all the images are getting serially, is there any way to do this in Batch?

**Comment by fcakyon** [comment]
@abhiksark  Since craft model requires high amount of gpu ram during inference, batch inference was not possible with a standart gpu for us. I may try adding batch support in the future but I wont be able to test it with my current gpu.

**Comment by abhiksark** [comment]
@fcakyon which GPU are you using?

**Comment by fcakyon** [comment]
@abhiksark tried on gpus with 4-6gb ram
