### ISSUE TITLE
Train on ICDAR 2O15

### ISSUE THREAD

**Issue by alinesoares1** [fcakyon/craft-text-detector#18]
It's possible to train this craft-text-detector on IC2015 database? How can I do it? Thanks

**Comment by fcakyon** [comment]
This repo has better coverage than IC2015, the provided weight is trained on SynthText, IC13, IC17 datasets.

Unfortunately training on new datasets is not supported with this repo, you can use [other projects](https://github.com/autonise/CRAFT-Remade)

**Comment by alinesoares1** [comment]
> This repo has better coverage than IC2015, the provided weight is trained on SynthText, IC13, IC17 datasets.
> 
> Unfortunately training on new datasets is not supported with this repo, you can use [other projects](https://github.com/autonise/CRAFT-Remade)

**Comment by fcakyon** [comment]
@alinesoares1 unfortunately I have not worried about the metrics while developing this repo but if someone sends a pr for evaluation metric support I would gladly accept it :)
