### ISSUE TITLE
Allow customized weights path in `load_*_model` utility functions

### ISSUE THREAD

**Issue by ruancomelli** [fcakyon/craft-text-detector#20]
First of all, thank you very much for this repo!

I came up with a situation in which I needed to use a different `weight_path` for storing CraftNet's and RefineNet's weights. However, the functions `load_craftnet_model` and `load_refinenet_model` define `weight_path` automatically as `$HOME/.craft_text_detector/weights/craft_*.pth`. It would be very useful to lift this restriction, allowing users to pass this path as a parameter when needed.

My idea is to rewrite those functions with a new signature `load_[craftnet/refinenet]_model(cuda: bool = False, weight_path=None)`. When `weight_path is None`, then we proceed as we do presently. However, if it is a valid path, then model weights should be saved to and loaded from that path.

**Comment by ruancomelli** [comment]
I am working on a PR to solve this.

**Comment by fcakyon** [comment]
you can use this feature in new release: `pip install -U craft-text-detector==0.3.2`
