### ISSUE TITLE
Relax requirements for OpenCV

### ISSUE THREAD

**Issue by ruancomelli** [fcakyon/craft-text-detector#24]
Hi again!

I am working on a project that uses CRAFT, but I also need a recent version of OpenCV (not sure of the specific version, but we are using `opencv-python==4.5.1.48`). The problem is that the current requirement, `opencv-python==3.4.8.29` is incompatible with it, so perhaps relaxing this requirement would allow broader use of this project. My workaround in my project was to install CRAFT's requirements, followed by `pip install opencv-python==4.5.1.48` and then `pip install --no-deps craft-text-detector`.

I replaced the current requirement with `opencv-python>=3.4.8.29` in my fork from `craft-text-detector`, OpenCV 4.5.1.48 is chosen by `pip`. All tests pass with this version, so I believe it would be feasible to use this new requirement.

What do you think? I'll shortly provide a PR for this.

**Comment by fcakyon** [comment]
@ruancomelli Makes sense, thanks for pointing it out.
