### ISSUE TITLE
Detect horizontal text only

### ISSUE THREAD

**Issue by guipaiva** [fcakyon/craft-text-detector#32]
I'm currently using craft on a project where I am interested only in horizontal text. At the moment I'm discarding the boxes in which the height is greater than the width, but this method fails sometimes. Is there any way to set the craft model to look for horizontal text only? 

Thanks in advance.

**Comment by fcakyon** [comment]
@guipaiva can you upload an test image so that i can replicate your issue better? Why is a simple aspect ratio check not enough for you?

There is no setting for horizontal only check in craft but a postprocessing for that purpose can be implemented. I just need to understand your need better.

**Comment by guipaiva** [comment]
@fcakyon I can't upload an example at the moment because there are sensitive data and I'm not authorized to share, but the aspect ratio check works most of the time but fails when the font size is too big and the text is too sparse to link with other words (almost always a single letter), then I get some boxes with height being larger than width. 

It would be useful if there was a parameter that indicated the rotation of the text so I could filter by that. 

I'll keep experimenting with aspect ratio and link threshold parameters, thank you for your time.

**Comment by fcakyon** [comment]
@guipaiva i totally understand your reasoning however, CRAFT does not predict the character orientation, it only predicts the region and affinity scores.
