### ISSUE TITLE
How can I use cuda for this project?

### ISSUE THREAD

**Issue by Shixian520** [fcakyon/craft-text-detector#35]
If I only use CPU, the speed is so slow, ao I am gonna use "cuda = True" for incresing the speed, but it does not work.  I have installed the right version of torch and the value of "torch.cuda.is_available()" is True.
If I set "cuda = True", the com does not work, although there are not any errors in dubugging, but does not work. What is the matter for this?

**Comment by fcakyon** [comment]
@Shixian520 thanks for your interest!

How are you sure `cuda = True` argument is not working? Have you checked GPU usage by `nvidia-smi` command? 

Unfortunately, GPU inference time is not not fast for craft text detection model.

**Comment by Shixian520** [comment]
OK, and then can you introduce some detect models with high speed and high accuracy? Thanks.

**Comment by Shixian520** [comment]
![image](https://user-images.githubusercontent.com/84282031/120983623-766ba300-c7ac-11eb-9332-f75849815eb4.png)
btw, this means GPU works well, right?

**Comment by fcakyon** [comment]
@Shixian520 yes this shows you can utilize GPU well.

I will work on better dataloader for faster batch inference when I have some time but there is no ETA.

**Comment by Shixian520** [comment]
I am trying to implement this project in other com, and have a strange error, like this. What does it mean?
![Screenshot_35](https://user-images.githubusercontent.com/84282031/121135007-a37c8c00-c866-11eb-8d22-420fb8ab7f18.png)

**Comment by fcakyon** [comment]
@Shixian520 It means it cannot download the weights automatically. Do you have internet connection on the other pc?
