### ISSUE TITLE
Negative and really small value for box points

### ISSUE THREAD

**Issue by jjavierdguezas** [fcakyon/craft-text-detector#36]
## 🐛 Bug

First, thanks for this lib, is extremely useful!

I noticed on one of the images I am processing that it sometimes returns negative and really small values for some box points
I am sorry but I cannot provide the image, I just think you should know and maybe check if the coordinates fall inside the image

## To Reproduce

```python
from craft_text_detector import get_prediction, load_craftnet_model, load_refinenet_model
# ...

    CUDA = False

    img = # ...

    refine_net = load_refinenet_model(cuda=CUDA)
    craft_net = load_craftnet_model(cuda=CUDA)
    prediction_result = get_prediction(
        image=img,
        craft_net=craft_net,
        refine_net=refine_net,
        text_threshold=0.55,
        link_threshold=0.6,
        low_text=0.3,
        cuda=CUDA,
        long_size=1280
    )

    for region in prediction_result["boxes"]:
        region[region < 0] = 0  # this is my fix for negative values
        # .....
```

some images showing the issue:

![image](https://user-images.githubusercontent.com/13673443/126616177-09f399ef-4125-47ba-beb1-38faba87f856.png)

![image](https://user-images.githubusercontent.com/13673443/126616089-c956cba2-6fd2-4d43-b7e4-e0b26ab9a1a6.png)

## Expected behavior

all boxes points fall inside the boundaries of the image

## Environment

 - craft-text-detector==0.3.5
 - Python version 3.8.10
 - Windows
 - How you installed craft-text-detector: pip

**Comment by fcakyon** [comment]
@jjavierdguezas really busy atm, will fix it as soon as possible, thanks for noting 👍 . By the meantime you can also open a pr including your fix mentioned abode ^^

**Comment by jjavierdguezas** [comment]
@fcakyon  The issue happens here https://github.com/fcakyon/craft-text-detector/blob/f77d8cebc3e9e2b9e79f75b337c127aeeb4b6e0f/craft_text_detector/craft_utils.py#L178-L179

I can see that some lines before that you do a boundary check, but later the `cv2.boxPoints(rectangle)` returns negative values

![image](https://user-images.githubusercontent.com/13673443/127629939-ed0ed0a2-460c-4bd4-8ac4-daf94a360d23.png)

Searching in the opencv doc I found [this](https://docs.opencv.org/3.4/d3/dc0/group__imgproc__shape.html#ga3d476a3417130ae5154aea421ca7ead9)
![image](https://user-images.githubusercontent.com/13673443/127630831-5b035755-07c9-4d6f-b796-c2db4878ec67.png)

So maybe we need to do a boundary check again. What do you think? I'd be happy to make a PR

**Comment by fcakyon** [comment]
@jjavierdguezas fantastic catch! i would gladly accept your pr 👍
