### ISSUE TITLE
Skip Model Loading

### ISSUE THREAD

**Issue by weihaulee** [fcakyon/craft-text-detector#41]
Hi, 

I'm trying to cut down the time taken to detect the texts.
What I found out is that the time taken to load model is the longest. (See picture below for the results)

![image](https://user-images.githubusercontent.com/87401246/133191384-833f3a8f-fb8f-4d57-bc15-aa34b5b4bb01.png)

Since the 'Craft load time' consist of these

![image](https://user-images.githubusercontent.com/87401246/133190934-75855c3e-5896-4a5b-9947-0a59f648dc20.png)

My idea is to create a if loop to check whether the model is loaded or not.
If it is loaded, then we can skip the model loading and proceed to the 'detect_text' function
Is there any way to do this? Based on the unload model functions, I can see that the model is loaded into Cuda/Cache.

Thank you.

**Comment by fcakyon** [comment]
@weihaulee thanks a lot for your interest!
It will load the craft model only at initilazation of the class, then each time you call `detect_text`, it will use the loaded model and wont load it again.
