### ISSUE TITLE
RGB Images are always converted to BGR during read_image()

### ISSUE THREAD

**Issue by annguyenfoss** [fcakyon/craft-text-detector#44]
## 🐛 Bug

`craft-text-detector` would always convert RGB image to BGR, thus rendering Red as Blue and etc etc

## To Reproduce

In `craft_text_detector/image_utils.py`

```
def read_image(image):
        if type(image) == str:
                img = cv2.imread(image)
                img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        ...
```
## Expected behavior

I'd like to ask if this is the desired behaviour, and if so, could you please elaborate more? if this is not the desired behaviour, then I would expect that RGB Image from Input will stay the same after CRAFT.

**Comment by fcakyon** [comment]
@annguyenfoss in the code snippet you sent above, all images are converted to RGB, not BGR. I don't understand the issue here.

What is the format of your original images? Black and white? RGB? 4 channel (including aplha) images?

**Comment by annguyenfoss** [comment]
Apologize if my information was confusing you.

My input image is RGB (I believe).

This is my original image and its crops: https://imgur.com/a/xEXxY3A

My desired behaviour is that the color of the outcome match the color of the original image. If this expectation is wrong, please help to clarify.

The code I used:

```python
from craft_text_detector import (
    load_craftnet_model,
    load_refinenet_model, get_prediction,
    export_detected_regions
)


def text_craft(image, output_dir, long_size):
    cuda = True
    refine_net = load_refinenet_model(cuda=cuda)
    craft_net = load_craftnet_model(cuda=cuda)
    prediction_result = get_prediction(
        image=image,
        craft_net=craft_net,
        refine_net=refine_net,
        text_threshold=0.7,
        link_threshold=0.1,
        low_text=0.4,
        cuda=cuda,
        long_size=long_size
    )
    export_detected_regions(
        image=image,
        regions=prediction_result["boxes"],
        output_dir=output_dir,
        rectify=True
    )

text_craft("test_img.png", ".", 1280)
```

## Environment
python==3.9.9
craft-text-detector==0.4.0
opencv-python==4.5.4.60

**Comment by fcakyon** [comment]
@annguyenfoss thanks for your valuable feedback!

Can you please uninstall `craft-text-detector`:

```bash
pip uninstall craft-text-detector
```

Then install `craft-text-detector` from `export` branch:

```bash
pip install git+https://github.com/fcakyon/craft-text-detector.git@export
```

And check if the issue is fixed?

**Comment by annguyenfoss** [comment]
Thank you, it worked great! Saw your code change, that explained everything. I was mistaken to look at `read_image()`

Kudos to you, good sir!

**Comment by fcakyon** [comment]
@annguyenfoss thank you too for spotting this issue! Have a good week 💯
