### ISSUE TITLE
Segmentation fault on new cv2 Version

### ISSUE THREAD

**Issue by krystofer47** [fcakyon/craft-text-detector#47]
## 🐛 Bug

The function call     
```python
nLabels, labels, stats, centroids = cv2.connectedComponentsWithStats(
    text_score_comb.astype(np.uint8), connectivity=4
)

```
in file https://github.com/fcakyon/craft-text-detector/blob/master/craft_text_detector/craft_utils.py line 136 lead to a segmentation fault. This problem does not appear when using opencv-python version 4.5.4.60. 

## To Reproduce

1. Install package with opencv-python=="4.5.5.62"
2. Run tests (havent tried it yet, at work atm. I have the package as dependency internally but I pretty much just use it like described in the readme)
3. Get segmentation fault (core dumped) error 

## Environment

 - craft-text-detector version: 0.4.1:
 - Python version: 3.8.6:
 - OS: Linux
 - How you installed craft-text-detector: pip
 - Any other relevant information: No

## Additional context

I have not tried any other opencv-python version, maybe they changed something internally which makes this function call break.

**Comment by krystofer47** [comment]
Yes that would be the solution, I doubt that any of the other dependencies do require the newest version of python-opencv which released just a few weeks back. But just to be sure it would probably be the best to run your unit tests to see if everything still works with the upperbound in place.

**Comment by fcakyon** [comment]
Till this bug is fixed on the opencv, lets fix the upperbound in craft-text-detector: https://github.com/opencv/opencv/issues/21366

All unittests pass with current upperbound for craft-text-detector: https://github.com/fcakyon/craft-text-detector/actions/runs/1662538164
