### ISSUE TITLE
Image Saving 

### ISSUE THREAD

**Issue by rajsaraiya009** [fcakyon/craft-text-detector#51]
Hello I tried with this model its working good, just needed to know every time I run it is stored in the path as we are giving the path if we  do not want to store the result in the path can we display the image after pre-processing ????

**Comment by MatteoLucarelli** [comment]
maybe you refer to export_detected_regions function?
In this case you're free to not call it and use get_prediction return value to perform your operation (such as display the identified crops with opencv highgui)

**Comment by fcakyon** [comment]
@MatteoLucarelli's suggestion is spot on!
