### ISSUE TITLE
CUDA switch not working in basic usage

### ISSUE THREAD

**Issue by gaborpelesz** [fcakyon/craft-text-detector#8]
## 🐛 Bug

Program crashes when trying to call 'Basic Usage' detect_text with CUDA turned on. The issue is that the program loads the models without considering the fact that CUDA migth be turned on.

## To Reproduce

1. call -> `craft.detect_text(image_path, outputs_craft, crop_type="poly", cuda=True)`

## Solution

I will create a Pull request to solve the unexpected crash, the solution is straightforward.

**Comment by fcakyon** [comment]
Thanks a lot for the feedback. You are definitely right, cuda/cpu switch is not working as intended. Will use your solution as a temporary fix, and will work on a better fix (thinking on a major refactorization)

**Comment by gaborpelesz** [comment]
Your welcome! 
I will continue discovering this repo as it is possible to be a piece in one of my projects. Really appreciate the great work. If anything else catches my eye, I'll let you know!

**Comment by fcakyon** [comment]
Glad to see you are making use of this repo! I'm open for any issue and pr's.

**Comment by fcakyon** [comment]
@gaborpelesz Hello again, now **v0.3.1** has a much cleaner basic usage backend, now you should be easily switching between devices and I have also added an option for clearing the gpu memory:
```python
# import Craft class
from craft_text_detector import Craft

# set image path and export folder directory
image_path = 'figures/idcard.png'
output_dir = 'outputs/'

# create a craft instance
craft = Craft(output_dir=output_dir, crop_type="poly", cuda=False)

# apply craft text detection and export detected regions to output directory
prediction_result = craft.detect_text(image_path)

# unload models from ram/gpu
craft.unload_craftnet_model()
craft.unload_refinenet_model()
```

**Comment by gaborpelesz** [comment]
@fcakyon Very nice! I'm not at home right now, but will definitely take a look in the upcoming weeks or so. Thanks for informing!
